algoritmo "porcentagem"
// Diciplina : PA
// Professora : Cínta
// Turma: A
// Data : 02/03/2023
// Nome : Isabely
var
nomep: caractere
custo,venda,porcentagem: real


//ENTRADA
inicio
escreva ("Nome do produto: ")
leia (nomep)

escreval ("Digite o valor do produto: ")
leia (custo)

//PROCESSAMENTO
porcentagem <- custo * 0.65

venda <- porcentagem + custo
// Saída
escreval ("O valor da venda do produto é: ", venda)


fimalgoritmo
