algoritmo "combustivel"
// Diciplina : PA
// Professora : Cínta
// Turma: A
// Data : 02/03/2023
// Nome : Isabely
var
dist,comb,med: real



//ENTRADA
inicio
escreva ("Digite a distância percorrida: ")
leia (dist)

escreval (" Escreva a quantidade de combustível gasta: ")
leia (comb)

//PROCESSAMENTO
med <- comb/dist


// Saída
escreval ("A média de combustível gasta em médiapor km é: ", med)


fimalgoritmo
