algoritmo "maior ou menor"
// Função : Verificar se o número é maior ou menor que 10
// Autor : Isabely
// Data : 24/05/2023
// Seção de Declarações
var

numero: real

inicio

escreval ("Digite um número:")
leia (numero)


//processamento

se (numero>10) entao
escreval ("seu número é maior que 10")

senao
escreval ("seu número é menor que 10")

fimse


// Seção de Comandos
fimalgoritmo