algoritmo "Numero entre 100 e 200"
// Função : Verificar se o número está entre 100 e 200
// Autor : Isabely
// Data : 24/05/2023
// Seção de Declarações
var

numero: real

inicio

escreval ("Digite um número:")
leia (numero)


//processamento

se ((numero>100) e (numero<200))entao
escreval ("Está entre 100 e 200")

senao
escreval ("Não está entre 100 e 200")


fimse


// Seção de Comandos
fimalgoritmo