algoritmo "Temperatura"
// Função : Verificar se a temperatura está fria, normal ou quente
// Autor : Isabely
// Data : 24/05/2023
// Seção de Declarações
var

temperatura: real

inicio

escreval ("Digite o valor da temperatura:")
leia (temperatura)


//processamento

se (temperatura<20) entao
escreval ("Está frio.")

senao (temperatura<25)
escreval ("Está normal")

senao
escreval ("Está quente")

fimse


// Seção de Comandos
fimalgoritmo